package client;
public enum Options{

    CUSTOMER_LOGIN,EMPLOYEE_LOGIN,
    CREATE_CUSTOMER,CREATE_EMPLOYEE,
    CREATE_COMPLAINT,UPDATE_COMPLAINT,
    DELETE_CUSTOMER, DELETE_EMPLOYEE,
    GET_COMPLAINT,DELETE_COMPLAINT,
    READ_ALL_COMPLAINT,CREATE_ACCOUNT,UPDATE_ACCOUNT,
    UPDATE_CUSTOMER,UPDATE_EMPLOYEE,DELETE_ACCOUNT,READ_ALL_CUSTOMER,
    READ_ALL_EMPLOYEE,READ_ALL_ACCOUNT,GET_CUSTOMER,GET_EMPLOYEE,GET_ACCOUNT,
}
