package client;
public enum Options{

    CUSTOMER_LOGIN,EMPLOYEE_LOGIN,
    CREATE_CUSTOMER,CREATE_EMPLOYEE,
    CREATE_COMPLAINT,UPDATE_COMPLAINT,
    DELETE_CUSTOMER, DELETE_EMPLOYEE,
    READ_COMPLAINT,DELETE_COMPLAINT,
    READ_ALL_COMPLAINT,CREATE_ACCOUNT,UPDATE_ACCOUNT,
    UPDATE_CUSTOMER,UPDATE_EMPLOYEE,
}
